### ISSUE TITLE
Set backgroundColor image

### ISSUE THREAD

**Issue by PieterCappelle** [staempfli/magento2-module-image-resizer#3]
Any plans to add functionality to change the background color? Default is white in Magento. 

https://github.com/magento/magento2/blob/develop/app/code/Magento/Catalog/Helper/Image.php

**Comment by jalogut** [comment]
Hi @PieterCappelle 

We did not have any plans to add this because the main purpose is just to resize images. However, I would be glad if you want to contribute with that. It should be an easy change, you would only need to add a couple of lines:

* $subPathSettingsMapping -> add new key `blackgroundColor`
* function resizeAndSaveImage() -> set `blackgroundColor` if it is defined into `$this->resizeSettings`

After this changes, you should be able to pass any blackground color to `resizeAndGetUrl()` in the `$resizeSettings` param

**Comment by jalogut** [comment]
Hi @PieterCappelle 

This functionality has been added in version 1.1.
